// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/exchange.proto

package exchange;

/**
 * Protobuf type {@code exchange.CurrencyUpdate}
 */
public  final class CurrencyUpdate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:exchange.CurrencyUpdate)
    CurrencyUpdateOrBuilder {
  // Use CurrencyUpdate.newBuilder() to construct.
  private CurrencyUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CurrencyUpdate() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CurrencyUpdate(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            exchange.CurrencyValue.Builder subBuilder = null;
            if (newCurrencyValue_ != null) {
              subBuilder = newCurrencyValue_.toBuilder();
            }
            newCurrencyValue_ = input.readMessage(exchange.CurrencyValue.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(newCurrencyValue_);
              newCurrencyValue_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return exchange.ExchangeOuterClass.internal_static_exchange_CurrencyUpdate_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return exchange.ExchangeOuterClass.internal_static_exchange_CurrencyUpdate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            exchange.CurrencyUpdate.class, exchange.CurrencyUpdate.Builder.class);
  }

  public static final int NEWCURRENCYVALUE_FIELD_NUMBER = 1;
  private exchange.CurrencyValue newCurrencyValue_;
  /**
   * <code>optional .exchange.CurrencyValue newCurrencyValue = 1;</code>
   */
  public boolean hasNewCurrencyValue() {
    return newCurrencyValue_ != null;
  }
  /**
   * <code>optional .exchange.CurrencyValue newCurrencyValue = 1;</code>
   */
  public exchange.CurrencyValue getNewCurrencyValue() {
    return newCurrencyValue_ == null ? exchange.CurrencyValue.getDefaultInstance() : newCurrencyValue_;
  }
  /**
   * <code>optional .exchange.CurrencyValue newCurrencyValue = 1;</code>
   */
  public exchange.CurrencyValueOrBuilder getNewCurrencyValueOrBuilder() {
    return getNewCurrencyValue();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (newCurrencyValue_ != null) {
      output.writeMessage(1, getNewCurrencyValue());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (newCurrencyValue_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getNewCurrencyValue());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof exchange.CurrencyUpdate)) {
      return super.equals(obj);
    }
    exchange.CurrencyUpdate other = (exchange.CurrencyUpdate) obj;

    boolean result = true;
    result = result && (hasNewCurrencyValue() == other.hasNewCurrencyValue());
    if (hasNewCurrencyValue()) {
      result = result && getNewCurrencyValue()
          .equals(other.getNewCurrencyValue());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasNewCurrencyValue()) {
      hash = (37 * hash) + NEWCURRENCYVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getNewCurrencyValue().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static exchange.CurrencyUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static exchange.CurrencyUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static exchange.CurrencyUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static exchange.CurrencyUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static exchange.CurrencyUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static exchange.CurrencyUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static exchange.CurrencyUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static exchange.CurrencyUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static exchange.CurrencyUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static exchange.CurrencyUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(exchange.CurrencyUpdate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code exchange.CurrencyUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:exchange.CurrencyUpdate)
      exchange.CurrencyUpdateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return exchange.ExchangeOuterClass.internal_static_exchange_CurrencyUpdate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return exchange.ExchangeOuterClass.internal_static_exchange_CurrencyUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              exchange.CurrencyUpdate.class, exchange.CurrencyUpdate.Builder.class);
    }

    // Construct using exchange.CurrencyUpdate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (newCurrencyValueBuilder_ == null) {
        newCurrencyValue_ = null;
      } else {
        newCurrencyValue_ = null;
        newCurrencyValueBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return exchange.ExchangeOuterClass.internal_static_exchange_CurrencyUpdate_descriptor;
    }

    public exchange.CurrencyUpdate getDefaultInstanceForType() {
      return exchange.CurrencyUpdate.getDefaultInstance();
    }

    public exchange.CurrencyUpdate build() {
      exchange.CurrencyUpdate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public exchange.CurrencyUpdate buildPartial() {
      exchange.CurrencyUpdate result = new exchange.CurrencyUpdate(this);
      if (newCurrencyValueBuilder_ == null) {
        result.newCurrencyValue_ = newCurrencyValue_;
      } else {
        result.newCurrencyValue_ = newCurrencyValueBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof exchange.CurrencyUpdate) {
        return mergeFrom((exchange.CurrencyUpdate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(exchange.CurrencyUpdate other) {
      if (other == exchange.CurrencyUpdate.getDefaultInstance()) return this;
      if (other.hasNewCurrencyValue()) {
        mergeNewCurrencyValue(other.getNewCurrencyValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      exchange.CurrencyUpdate parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (exchange.CurrencyUpdate) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private exchange.CurrencyValue newCurrencyValue_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        exchange.CurrencyValue, exchange.CurrencyValue.Builder, exchange.CurrencyValueOrBuilder> newCurrencyValueBuilder_;
    /**
     * <code>optional .exchange.CurrencyValue newCurrencyValue = 1;</code>
     */
    public boolean hasNewCurrencyValue() {
      return newCurrencyValueBuilder_ != null || newCurrencyValue_ != null;
    }
    /**
     * <code>optional .exchange.CurrencyValue newCurrencyValue = 1;</code>
     */
    public exchange.CurrencyValue getNewCurrencyValue() {
      if (newCurrencyValueBuilder_ == null) {
        return newCurrencyValue_ == null ? exchange.CurrencyValue.getDefaultInstance() : newCurrencyValue_;
      } else {
        return newCurrencyValueBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .exchange.CurrencyValue newCurrencyValue = 1;</code>
     */
    public Builder setNewCurrencyValue(exchange.CurrencyValue value) {
      if (newCurrencyValueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        newCurrencyValue_ = value;
        onChanged();
      } else {
        newCurrencyValueBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .exchange.CurrencyValue newCurrencyValue = 1;</code>
     */
    public Builder setNewCurrencyValue(
        exchange.CurrencyValue.Builder builderForValue) {
      if (newCurrencyValueBuilder_ == null) {
        newCurrencyValue_ = builderForValue.build();
        onChanged();
      } else {
        newCurrencyValueBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .exchange.CurrencyValue newCurrencyValue = 1;</code>
     */
    public Builder mergeNewCurrencyValue(exchange.CurrencyValue value) {
      if (newCurrencyValueBuilder_ == null) {
        if (newCurrencyValue_ != null) {
          newCurrencyValue_ =
            exchange.CurrencyValue.newBuilder(newCurrencyValue_).mergeFrom(value).buildPartial();
        } else {
          newCurrencyValue_ = value;
        }
        onChanged();
      } else {
        newCurrencyValueBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .exchange.CurrencyValue newCurrencyValue = 1;</code>
     */
    public Builder clearNewCurrencyValue() {
      if (newCurrencyValueBuilder_ == null) {
        newCurrencyValue_ = null;
        onChanged();
      } else {
        newCurrencyValue_ = null;
        newCurrencyValueBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .exchange.CurrencyValue newCurrencyValue = 1;</code>
     */
    public exchange.CurrencyValue.Builder getNewCurrencyValueBuilder() {
      
      onChanged();
      return getNewCurrencyValueFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .exchange.CurrencyValue newCurrencyValue = 1;</code>
     */
    public exchange.CurrencyValueOrBuilder getNewCurrencyValueOrBuilder() {
      if (newCurrencyValueBuilder_ != null) {
        return newCurrencyValueBuilder_.getMessageOrBuilder();
      } else {
        return newCurrencyValue_ == null ?
            exchange.CurrencyValue.getDefaultInstance() : newCurrencyValue_;
      }
    }
    /**
     * <code>optional .exchange.CurrencyValue newCurrencyValue = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        exchange.CurrencyValue, exchange.CurrencyValue.Builder, exchange.CurrencyValueOrBuilder> 
        getNewCurrencyValueFieldBuilder() {
      if (newCurrencyValueBuilder_ == null) {
        newCurrencyValueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            exchange.CurrencyValue, exchange.CurrencyValue.Builder, exchange.CurrencyValueOrBuilder>(
                getNewCurrencyValue(),
                getParentForChildren(),
                isClean());
        newCurrencyValue_ = null;
      }
      return newCurrencyValueBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:exchange.CurrencyUpdate)
  }

  // @@protoc_insertion_point(class_scope:exchange.CurrencyUpdate)
  private static final exchange.CurrencyUpdate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new exchange.CurrencyUpdate();
  }

  public static exchange.CurrencyUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CurrencyUpdate>
      PARSER = new com.google.protobuf.AbstractParser<CurrencyUpdate>() {
    public CurrencyUpdate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CurrencyUpdate(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CurrencyUpdate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CurrencyUpdate> getParserForType() {
    return PARSER;
  }

  public exchange.CurrencyUpdate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

