// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/exchange.proto

package exchange;

public interface CurrenciesListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exchange.CurrenciesList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .exchange.Currency currencies = 1;</code>
   */
  java.util.List<exchange.Currency> getCurrenciesList();
  /**
   * <code>repeated .exchange.Currency currencies = 1;</code>
   */
  int getCurrenciesCount();
  /**
   * <code>repeated .exchange.Currency currencies = 1;</code>
   */
  exchange.Currency getCurrencies(int index);
  /**
   * <code>repeated .exchange.Currency currencies = 1;</code>
   */
  java.util.List<java.lang.Integer>
  getCurrenciesValueList();
  /**
   * <code>repeated .exchange.Currency currencies = 1;</code>
   */
  int getCurrenciesValue(int index);
}
