// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/exchange.proto

package exchange;

/**
 * Protobuf type {@code exchange.CurrenciesList}
 */
public  final class CurrenciesList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:exchange.CurrenciesList)
    CurrenciesListOrBuilder {
  // Use CurrenciesList.newBuilder() to construct.
  private CurrenciesList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CurrenciesList() {
    currencies_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private CurrenciesList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              currencies_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000001;
            }
            currencies_.add(rawValue);
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int oldLimit = input.pushLimit(length);
            while(input.getBytesUntilLimit() > 0) {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                currencies_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              currencies_.add(rawValue);
            }
            input.popLimit(oldLimit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        currencies_ = java.util.Collections.unmodifiableList(currencies_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return exchange.ExchangeOuterClass.internal_static_exchange_CurrenciesList_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return exchange.ExchangeOuterClass.internal_static_exchange_CurrenciesList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            exchange.CurrenciesList.class, exchange.CurrenciesList.Builder.class);
  }

  public static final int CURRENCIES_FIELD_NUMBER = 1;
  private java.util.List<java.lang.Integer> currencies_;
  private static final com.google.protobuf.Internal.ListAdapter.Converter<
      java.lang.Integer, exchange.Currency> currencies_converter_ =
          new com.google.protobuf.Internal.ListAdapter.Converter<
              java.lang.Integer, exchange.Currency>() {
            public exchange.Currency convert(java.lang.Integer from) {
              exchange.Currency result = exchange.Currency.valueOf(from);
              return result == null ? exchange.Currency.UNRECOGNIZED : result;
            }
          };
  /**
   * <code>repeated .exchange.Currency currencies = 1;</code>
   */
  public java.util.List<exchange.Currency> getCurrenciesList() {
    return new com.google.protobuf.Internal.ListAdapter<
        java.lang.Integer, exchange.Currency>(currencies_, currencies_converter_);
  }
  /**
   * <code>repeated .exchange.Currency currencies = 1;</code>
   */
  public int getCurrenciesCount() {
    return currencies_.size();
  }
  /**
   * <code>repeated .exchange.Currency currencies = 1;</code>
   */
  public exchange.Currency getCurrencies(int index) {
    return currencies_converter_.convert(currencies_.get(index));
  }
  /**
   * <code>repeated .exchange.Currency currencies = 1;</code>
   */
  public java.util.List<java.lang.Integer>
  getCurrenciesValueList() {
    return currencies_;
  }
  /**
   * <code>repeated .exchange.Currency currencies = 1;</code>
   */
  public int getCurrenciesValue(int index) {
    return currencies_.get(index);
  }
  private int currenciesMemoizedSerializedSize;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getCurrenciesList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(currenciesMemoizedSerializedSize);
    }
    for (int i = 0; i < currencies_.size(); i++) {
      output.writeEnumNoTag(currencies_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < currencies_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeEnumSizeNoTag(currencies_.get(i));
      }
      size += dataSize;
      if (!getCurrenciesList().isEmpty()) {  size += 1;
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32SizeNoTag(dataSize);
      }currenciesMemoizedSerializedSize = dataSize;
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof exchange.CurrenciesList)) {
      return super.equals(obj);
    }
    exchange.CurrenciesList other = (exchange.CurrenciesList) obj;

    boolean result = true;
    result = result && currencies_.equals(other.currencies_);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getCurrenciesCount() > 0) {
      hash = (37 * hash) + CURRENCIES_FIELD_NUMBER;
      hash = (53 * hash) + currencies_.hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static exchange.CurrenciesList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static exchange.CurrenciesList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static exchange.CurrenciesList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static exchange.CurrenciesList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static exchange.CurrenciesList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static exchange.CurrenciesList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static exchange.CurrenciesList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static exchange.CurrenciesList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static exchange.CurrenciesList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static exchange.CurrenciesList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(exchange.CurrenciesList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code exchange.CurrenciesList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:exchange.CurrenciesList)
      exchange.CurrenciesListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return exchange.ExchangeOuterClass.internal_static_exchange_CurrenciesList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return exchange.ExchangeOuterClass.internal_static_exchange_CurrenciesList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              exchange.CurrenciesList.class, exchange.CurrenciesList.Builder.class);
    }

    // Construct using exchange.CurrenciesList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      currencies_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return exchange.ExchangeOuterClass.internal_static_exchange_CurrenciesList_descriptor;
    }

    public exchange.CurrenciesList getDefaultInstanceForType() {
      return exchange.CurrenciesList.getDefaultInstance();
    }

    public exchange.CurrenciesList build() {
      exchange.CurrenciesList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public exchange.CurrenciesList buildPartial() {
      exchange.CurrenciesList result = new exchange.CurrenciesList(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        currencies_ = java.util.Collections.unmodifiableList(currencies_);
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.currencies_ = currencies_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof exchange.CurrenciesList) {
        return mergeFrom((exchange.CurrenciesList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(exchange.CurrenciesList other) {
      if (other == exchange.CurrenciesList.getDefaultInstance()) return this;
      if (!other.currencies_.isEmpty()) {
        if (currencies_.isEmpty()) {
          currencies_ = other.currencies_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureCurrenciesIsMutable();
          currencies_.addAll(other.currencies_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      exchange.CurrenciesList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (exchange.CurrenciesList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<java.lang.Integer> currencies_ =
      java.util.Collections.emptyList();
    private void ensureCurrenciesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        currencies_ = new java.util.ArrayList<java.lang.Integer>(currencies_);
        bitField0_ |= 0x00000001;
      }
    }
    /**
     * <code>repeated .exchange.Currency currencies = 1;</code>
     */
    public java.util.List<exchange.Currency> getCurrenciesList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, exchange.Currency>(currencies_, currencies_converter_);
    }
    /**
     * <code>repeated .exchange.Currency currencies = 1;</code>
     */
    public int getCurrenciesCount() {
      return currencies_.size();
    }
    /**
     * <code>repeated .exchange.Currency currencies = 1;</code>
     */
    public exchange.Currency getCurrencies(int index) {
      return currencies_converter_.convert(currencies_.get(index));
    }
    /**
     * <code>repeated .exchange.Currency currencies = 1;</code>
     */
    public Builder setCurrencies(
        int index, exchange.Currency value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureCurrenciesIsMutable();
      currencies_.set(index, value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .exchange.Currency currencies = 1;</code>
     */
    public Builder addCurrencies(exchange.Currency value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureCurrenciesIsMutable();
      currencies_.add(value.getNumber());
      onChanged();
      return this;
    }
    /**
     * <code>repeated .exchange.Currency currencies = 1;</code>
     */
    public Builder addAllCurrencies(
        java.lang.Iterable<? extends exchange.Currency> values) {
      ensureCurrenciesIsMutable();
      for (exchange.Currency value : values) {
        currencies_.add(value.getNumber());
      }
      onChanged();
      return this;
    }
    /**
     * <code>repeated .exchange.Currency currencies = 1;</code>
     */
    public Builder clearCurrencies() {
      currencies_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .exchange.Currency currencies = 1;</code>
     */
    public java.util.List<java.lang.Integer>
    getCurrenciesValueList() {
      return java.util.Collections.unmodifiableList(currencies_);
    }
    /**
     * <code>repeated .exchange.Currency currencies = 1;</code>
     */
    public int getCurrenciesValue(int index) {
      return currencies_.get(index);
    }
    /**
     * <code>repeated .exchange.Currency currencies = 1;</code>
     */
    public Builder setCurrenciesValue(
        int index, int value) {
      ensureCurrenciesIsMutable();
      currencies_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .exchange.Currency currencies = 1;</code>
     */
    public Builder addCurrenciesValue(int value) {
      ensureCurrenciesIsMutable();
      currencies_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated .exchange.Currency currencies = 1;</code>
     */
    public Builder addAllCurrenciesValue(
        java.lang.Iterable<java.lang.Integer> values) {
      ensureCurrenciesIsMutable();
      for (int value : values) {
        currencies_.add(value);
      }
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:exchange.CurrenciesList)
  }

  // @@protoc_insertion_point(class_scope:exchange.CurrenciesList)
  private static final exchange.CurrenciesList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new exchange.CurrenciesList();
  }

  public static exchange.CurrenciesList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CurrenciesList>
      PARSER = new com.google.protobuf.AbstractParser<CurrenciesList>() {
    public CurrenciesList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new CurrenciesList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CurrenciesList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CurrenciesList> getParserForType() {
    return PARSER;
  }

  public exchange.CurrenciesList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

