// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/exchange.proto

package exchange;

public interface CurrencyUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exchange.CurrencyUpdate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .exchange.CurrencyValue newCurrencyValue = 1;</code>
   */
  boolean hasNewCurrencyValue();
  /**
   * <code>optional .exchange.CurrencyValue newCurrencyValue = 1;</code>
   */
  exchange.CurrencyValue getNewCurrencyValue();
  /**
   * <code>optional .exchange.CurrencyValue newCurrencyValue = 1;</code>
   */
  exchange.CurrencyValueOrBuilder getNewCurrencyValueOrBuilder();
}
