// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/exchange.proto

package exchange;

public interface CurrencyValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:exchange.CurrencyValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .exchange.Currency currency = 1;</code>
   */
  int getCurrencyValue();
  /**
   * <code>optional .exchange.Currency currency = 1;</code>
   */
  exchange.Currency getCurrency();

  /**
   * <code>optional double value = 2;</code>
   */
  double getValue();
}
