// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/exchange.proto

package exchange;

public final class ExchangeOuterClass {
  private ExchangeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exchange_CurrenciesList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_exchange_CurrenciesList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exchange_CurrencyValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_exchange_CurrencyValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exchange_CurrencyUpdate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_exchange_CurrencyUpdate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'src/main/resources/proto/exchange.prot" +
      "o\022\010exchange\"8\n\016CurrenciesList\022&\n\ncurrenc" +
      "ies\030\001 \003(\0162\022.exchange.Currency\"D\n\rCurrenc" +
      "yValue\022$\n\010currency\030\001 \001(\0162\022.exchange.Curr" +
      "ency\022\r\n\005value\030\002 \001(\001\"C\n\016CurrencyUpdate\0221\n" +
      "\020newCurrencyValue\030\001 \001(\0132\027.exchange.Curre" +
      "ncyValue*7\n\010Currency\022\007\n\003PLN\020\000\022\007\n\003EUR\020\001\022\007" +
      "\n\003USD\020\002\022\007\n\003GBP\020\003\022\007\n\003JPY\020\0042Y\n\010Exchange\022M\n" +
      "\023subscribeToExchange\022\030.exchange.Currenci" +
      "esList\032\030.exchange.CurrencyUpdate\"\0000\001B\014\n\010",
      "exchangeP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_exchange_CurrenciesList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_exchange_CurrenciesList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_exchange_CurrenciesList_descriptor,
        new java.lang.String[] { "Currencies", });
    internal_static_exchange_CurrencyValue_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_exchange_CurrencyValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_exchange_CurrencyValue_descriptor,
        new java.lang.String[] { "Currency", "Value", });
    internal_static_exchange_CurrencyUpdate_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_exchange_CurrencyUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_exchange_CurrencyUpdate_descriptor,
        new java.lang.String[] { "NewCurrencyValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
