// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `bank.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Bank;

public class Account implements java.lang.Cloneable,
                                java.io.Serializable
{
    public String firstName;

    public String secondName;

    public String pesel;

    public AccountType type;

    public AccountStateHandlerPrx accountStateHandler;

    public Account()
    {
        this.firstName = "";
        this.secondName = "";
        this.pesel = "";
        this.type = AccountType.STANDARD;
    }

    public Account(String firstName, String secondName, String pesel, AccountType type, AccountStateHandlerPrx accountStateHandler)
    {
        this.firstName = firstName;
        this.secondName = secondName;
        this.pesel = pesel;
        this.type = type;
        this.accountStateHandler = accountStateHandler;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Account r = null;
        if(rhs instanceof Account)
        {
            r = (Account)rhs;
        }

        if(r != null)
        {
            if(this.firstName != r.firstName)
            {
                if(this.firstName == null || r.firstName == null || !this.firstName.equals(r.firstName))
                {
                    return false;
                }
            }
            if(this.secondName != r.secondName)
            {
                if(this.secondName == null || r.secondName == null || !this.secondName.equals(r.secondName))
                {
                    return false;
                }
            }
            if(this.pesel != r.pesel)
            {
                if(this.pesel == null || r.pesel == null || !this.pesel.equals(r.pesel))
                {
                    return false;
                }
            }
            if(this.type != r.type)
            {
                if(this.type == null || r.type == null || !this.type.equals(r.type))
                {
                    return false;
                }
            }
            if(this.accountStateHandler != r.accountStateHandler)
            {
                if(this.accountStateHandler == null || r.accountStateHandler == null || !this.accountStateHandler.equals(r.accountStateHandler))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Bank::Account");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, firstName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, secondName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, pesel);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, type);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, accountStateHandler);
        return h_;
    }

    public Account clone()
    {
        Account c = null;
        try
        {
            c = (Account)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.firstName);
        ostr.writeString(this.secondName);
        ostr.writeString(this.pesel);
        AccountType.ice_write(ostr, this.type);
        ostr.writeProxy(this.accountStateHandler);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.firstName = istr.readString();
        this.secondName = istr.readString();
        this.pesel = istr.readString();
        this.type = AccountType.ice_read(istr);
        this.accountStateHandler = AccountStateHandlerPrx.uncheckedCast(istr.readProxy());
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Account v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Account ice_read(com.zeroc.Ice.InputStream istr)
    {
        Account v = new Account();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Account> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Account v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Account> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Account.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Account _nullMarshalValue = new Account();

    public static final long serialVersionUID = 6836964874063606808L;
}
