// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `bank.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Bank;

public interface AccountStateHandlerPrx extends com.zeroc.Ice.ObjectPrx
{
    default AccountState checkAccountState()
    {
        return checkAccountState(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default AccountState checkAccountState(java.util.Map<String, String> context)
    {
        return _iceI_checkAccountStateAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<AccountState> checkAccountStateAsync()
    {
        return _iceI_checkAccountStateAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<AccountState> checkAccountStateAsync(java.util.Map<String, String> context)
    {
        return _iceI_checkAccountStateAsync(context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<AccountState> _iceI_checkAccountStateAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<AccountState> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "checkAccountState", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     AccountState ret;
                     ret = AccountState.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void getTransfer(Currency currency, double value)
    {
        getTransfer(currency, value, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void getTransfer(Currency currency, double value, java.util.Map<String, String> context)
    {
        _iceI_getTransferAsync(currency, value, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> getTransferAsync(Currency currency, double value)
    {
        return _iceI_getTransferAsync(currency, value, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> getTransferAsync(Currency currency, double value, java.util.Map<String, String> context)
    {
        return _iceI_getTransferAsync(currency, value, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_getTransferAsync(Currency iceP_currency, double iceP_value, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getTransfer", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     Currency.ice_write(ostr, iceP_currency);
                     ostr.writeDouble(iceP_value);
                 }, null);
        return f;
    }

    default void makeTransfer(Currency currency, double value)
        throws NotEnoughMoneyException
    {
        makeTransfer(currency, value, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void makeTransfer(Currency currency, double value, java.util.Map<String, String> context)
        throws NotEnoughMoneyException
    {
        try
        {
            _iceI_makeTransferAsync(currency, value, context, true).waitForResponseOrUserEx();
        }
        catch(NotEnoughMoneyException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> makeTransferAsync(Currency currency, double value)
    {
        return _iceI_makeTransferAsync(currency, value, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> makeTransferAsync(Currency currency, double value, java.util.Map<String, String> context)
    {
        return _iceI_makeTransferAsync(currency, value, context, false);
    }

    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_makeTransferAsync(Currency iceP_currency, double iceP_value, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "makeTransfer", null, sync, _iceE_makeTransfer);
        f.invoke(true, context, null, ostr -> {
                     Currency.ice_write(ostr, iceP_currency);
                     ostr.writeDouble(iceP_value);
                 }, null);
        return f;
    }

    static final Class<?>[] _iceE_makeTransfer =
    {
        NotEnoughMoneyException.class
    };

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AccountStateHandlerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), AccountStateHandlerPrx.class, _AccountStateHandlerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AccountStateHandlerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), AccountStateHandlerPrx.class, _AccountStateHandlerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AccountStateHandlerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), AccountStateHandlerPrx.class, _AccountStateHandlerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static AccountStateHandlerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), AccountStateHandlerPrx.class, _AccountStateHandlerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static AccountStateHandlerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, AccountStateHandlerPrx.class, _AccountStateHandlerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static AccountStateHandlerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, AccountStateHandlerPrx.class, _AccountStateHandlerPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default AccountStateHandlerPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (AccountStateHandlerPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default AccountStateHandlerPrx ice_adapterId(String newAdapterId)
    {
        return (AccountStateHandlerPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default AccountStateHandlerPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (AccountStateHandlerPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default AccountStateHandlerPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (AccountStateHandlerPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default AccountStateHandlerPrx ice_invocationTimeout(int newTimeout)
    {
        return (AccountStateHandlerPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default AccountStateHandlerPrx ice_connectionCached(boolean newCache)
    {
        return (AccountStateHandlerPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default AccountStateHandlerPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (AccountStateHandlerPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default AccountStateHandlerPrx ice_secure(boolean b)
    {
        return (AccountStateHandlerPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default AccountStateHandlerPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (AccountStateHandlerPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default AccountStateHandlerPrx ice_preferSecure(boolean b)
    {
        return (AccountStateHandlerPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default AccountStateHandlerPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (AccountStateHandlerPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default AccountStateHandlerPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (AccountStateHandlerPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default AccountStateHandlerPrx ice_collocationOptimized(boolean b)
    {
        return (AccountStateHandlerPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default AccountStateHandlerPrx ice_twoway()
    {
        return (AccountStateHandlerPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default AccountStateHandlerPrx ice_oneway()
    {
        return (AccountStateHandlerPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default AccountStateHandlerPrx ice_batchOneway()
    {
        return (AccountStateHandlerPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default AccountStateHandlerPrx ice_datagram()
    {
        return (AccountStateHandlerPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default AccountStateHandlerPrx ice_batchDatagram()
    {
        return (AccountStateHandlerPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default AccountStateHandlerPrx ice_compress(boolean co)
    {
        return (AccountStateHandlerPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default AccountStateHandlerPrx ice_timeout(int t)
    {
        return (AccountStateHandlerPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default AccountStateHandlerPrx ice_connectionId(String connectionId)
    {
        return (AccountStateHandlerPrx)_ice_connectionId(connectionId);
    }

    static String ice_staticId()
    {
        return "::Bank::AccountStateHandler";
    }
}
