// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `bank.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Bank;

public class NotEnoughMoneyException extends GenericException
{
    public NotEnoughMoneyException()
    {
        super();
    }

    public NotEnoughMoneyException(Throwable cause)
    {
        super(cause);
    }

    public NotEnoughMoneyException(String message)
    {
        super(message);
    }

    public NotEnoughMoneyException(String message, Throwable cause)
    {
        super(message, cause);
    }

    public String ice_id()
    {
        return "::Bank::NotEnoughMoneyException";
    }

    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::Bank::NotEnoughMoneyException", -1, false);
        ostr_.endSlice();
        super._writeImpl(ostr_);
    }

    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        istr_.endSlice();
        super._readImpl(istr_);
    }

    public static final long serialVersionUID = 6378133685946550509L;
}
